config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'daily_scorecards#today'

  get '/settings', to: 'users#edit', as: 'settings'
  patch '/settings', to: 'users#update'

  get '/', to: 'daily_scorecards#today', as: 'daily_scorecard_today'

  get '/:year/:month/:day', to: 'daily_scorecards#show', as: 'daily_scorecard',
    constraints: { :year => /\d+/, :month => /\d\d?/, :day => /\d\d?/ }

  scope '/:year/:month/:day' do
    resources :meals, only: [:new, :create]
  end

  resources :meals, only: [:edit, :update, :destroy] do
    resources :foods, except: [:index, :show]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  around_filter :set_time_zone

  def set_time_zone(&block)
    if user_signed_in?
      Time.use_zone(current_user.timezone, &block)
    else
      yield
    end
  end

  module HasServices
    def self.extended(klass)
      klass.include(InstanceMethods)
    end

    def service(name, &block)
      attr_writer name
      private "#{name}="

      define_method(name) do
        instance_variable_get("@#{name}") \
          || instance_variable_set("@#{name}", instance_eval(&block))
      end
    end

    module InstanceMethods
      def load_services(services = {})
        services.each do |name, instance|
          self.send("#{name}=", instance)
        end
      end
    end
  end

  extend HasServices

  module HasTemplateAttrs
    def template_attr(*names)
      attr_accessor *names
      helper_method *names
      private *names.map { |name| "#{name}=" }
    end
  end

  extend HasTemplateAttrs

  private

  def date_params_from(date)
    {:year => date.year, :month => date.month, :day => date.day}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_error_classes(errors)
    if errors.any?
      'has-error has-feedback'
    else
      ''
    end
  end

  def render_flash_messages(obj)
    case obj
    when String
      obj
    else
      t(obj.delete('key'), obj.symbolize_keys)
    end
  end
end

app/views/application/_alert.html.erb
<div class="alert alert-warning alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= render_flash_messages(alert) %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Diet Scorecard</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('settings'), settings_path %></li>
              <li class="divider"></li>
              <li><%= link_to t('sign_out'), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_notice.html.erb
<div class="alert alert-info alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%=t notice.delete('key'), notice.symbolize_keys %>
</div>